Repository stolostron/search-indexer, pull requests merged in 2022-01, with the labels that each got.

#8 Adding files for prow onboarding
  Dockerfile.prow
  Makefile.prow
  OWNERS
Labels: lgtm

#5 Insert data into PostgreSQL
  Dockerfile
  Dockerfile.prow
  Makefile
  go.mod
  go.sum
  main.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/database/connection.go
  pkg/database/connection_test.go
  pkg/database/mocks/simple.json
  pkg/database/resync.go
  pkg/database/resync_test.go
  pkg/database/sync.go
  pkg/database/sync_test.go
  pkg/database/testHelper_test.go
  pkg/server/mocks/clearAll.json
  pkg/server/mocks/clusterA.json
  pkg/server/mocks/clusterB.json
  pkg/server/mocks/local-cluster.json
  pkg/server/mocks/more.json
  pkg/server/mocks/simple-delete.json
  pkg/server/mocks/simple-update.json
  pkg/server/server.go
  pkg/server/syncHandler.go
  pkg/server/syncHandler_test.go
  pkg/server/testHelper_test.go
  test/locust-clusters.py
Labels: lgtm, approved

#9 more fields from edges
  pkg/database/connection.go
  pkg/database/connection_test.go
  pkg/database/sync.go
Labels: lgtm, approved

#10 Enable lint and fix initial errors
  Makefile
  Makefile.prow
  README.md
  go.mod
  pkg/database/connection.go
  pkg/database/resync_test.go
  pkg/database/sync_test.go
  pkg/database/testHelper_test.go
  pkg/server/syncHandler_test.go
  pkg/server/testHelper_test.go
Labels: lgtm, approved

#11 primary key edges table
  pkg/database/connection.go
  pkg/database/connection_test.go
Labels: lgtm, approved

#14 Revert "primary key edges table"
  pkg/database/connection.go
  pkg/database/connection_test.go
Labels: lgtm, approved

#15 URL encode the database password
  pkg/config/config.go
Labels: lgtm, approved

#16 Create search schema to add tables
  go.mod
  pkg/database/connection.go
  pkg/database/connection_test.go
  pkg/database/resync.go
  pkg/database/resync_test.go
  pkg/database/sync.go
  sonar.project.properties
Labels: lgtm, approved

#18 Fix prow builds
  COMPONENT_NAME
  sonar-project.properties
Labels: lgtm, approved

#19 Check for errors (gosec)
  Makefile
  Makefile.prow
  pkg/database/connection.go
  pkg/database/connection_test.go
  pkg/database/sync.go
Labels: lgtm, approved

#20 Update sonar coverage reporting
  sonar-project.properties
Labels: lgtm, approved

#21 Add DCO
  DCO
  README.md
Labels: lgtm, approved

#26 Fix scale tests - unique uids
  sonar-project.properties
  test/cluster-template.json
  test/locust-clusters.py
Labels: lgtm, approved

#28 Add jsonb indexing for kind, name, and namespace
  benchmark.md
  pkg/database/connection.go
  pkg/database/connection_test.go
  pkg/database/sync.go
Labels: lgtm, approved, dco-signoff: yes

#27 Don't drop schema at startup in production
  Makefile
  go.mod
  go.sum
  pkg/config/config.go
  pkg/config/config_development.go
  pkg/database/connection.go
  pkg/database/connection_test.go
Labels: lgtm, approved, dco-signoff: yes

#29 Fix bugs from merging PR #27
  pkg/config/config_development.go
  pkg/database/connection.go
  pkg/database/connection_test.go
Labels: lgtm, approved, dco-signoff: yes
